"""
Valitine — Mode 2: Business Checks
Check semantic correctness of specific columns.
Each check updates a living report file for the table.
"""

import re
import pandas as pd
from datetime import datetime
from pathlib import Path


# ─────────────────────────────────────────────
# Internal: Report file management
# ─────────────────────────────────────────────

def _get_report_path(table: str, output_dir: str) -> Path:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    return Path(output_dir) / f"{table}_business_check.md"


def _load_or_init_report(df: pd.DataFrame, table: str, output_dir: str) -> dict:
    path = _get_report_path(table, output_dir)
    if path.exists():
        state = _parse_existing_report(path, df)
    else:
        state = {col: {"check": None, "status": "⬜ pending", "issues": "", "updated": ""} for col in df.columns}
    return state


def _parse_existing_report(path: Path, df: pd.DataFrame) -> dict:
    state = {col: {"check": None, "status": "⬜ pending", "issues": "", "updated": ""} for col in df.columns}
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
    for line in lines:
        if not line.startswith("|") or "Column" in line or "---" in line:
            continue
        parts = [p.strip() for p in line.strip().strip("|").split("|")]
        if len(parts) < 6:
            continue
        col_name = parts[1].strip("`")
        if col_name in state:
            state[col_name] = {
                "check": parts[2] if parts[2] != "—" else None,
                "status": parts[3],
                "issues": parts[4] if parts[4] != "—" else "",
                "updated": parts[5] if len(parts) > 5 else "",
            }
    return state


def _save_report(state: dict, table: str, output_dir: str, df_cols: list):
    path = _get_report_path(table, output_dir)
    run_date = datetime.now().strftime("%Y-%m-%d %H:%M")

    checked = sum(1 for v in state.values() if v["check"] is not None and v["status"] != "— skip")
    skipped = sum(1 for v in state.values() if v["status"] == "— skip")
    total = len(state)

    lines = []
    lines.append("# Valitine — Mode 2: Business Check")
    lines.append("")
    lines.append(f"**Table:** `{table}`  ")
    lines.append(f"**Last updated:** {run_date}  ")
    lines.append(f"**Progress:** {checked}/{total} columns checked  &nbsp;|&nbsp;  {skipped} skipped")
    lines.append("")
    lines.append("## Column Checklist")
    lines.append("")
    lines.append("| # | Column | Check Applied | Status | Issues | Updated |")
    lines.append("|---|--------|---------------|--------|--------|---------|")

    for i, col in enumerate(df_cols, 1):
        s = state.get(col, {"check": None, "status": "⬜ pending", "issues": "", "updated": ""})
        check_applied = s["check"] if s["check"] else "—"
        issues = s["issues"].split("\n")[0][:80] if s["issues"] else "—"  # first line only in table
        updated = s["updated"] if s["updated"] else "—"
        lines.append(f"| {i} | `{col}` | {check_applied} | {s['status']} | {issues} | {updated} |")

    lines.append("")

    # Issue detail section
    issue_cols = [(col, s) for col, s in state.items() if s.get("issues") and s["status"] != "— skip"]
    if issue_cols:
        lines.append("## Issue Details")
        lines.append("")
        for col, s in issue_cols:
            lines.append(f"### `{col}`")
            lines.append(s["issues"])
            lines.append("")

    lines.append("---")
    lines.append("*Generated by Valitine — Mode 2 (Business Check)*  ")
    lines.append("*⬜ pending = ยังไม่ได้เช็ค &nbsp;|&nbsp; — skip = ไม่จำเป็นต้องเช็ค (กรอกเองได้)*")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[Valitine] Mode 2 report updated → {path}")


def _update_col(df, col, table, output_dir, check_name, issues, passed):
    state = _load_or_init_report(df, table, output_dir)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    status = "✅ pass" if passed else "⚠️ warn"
    issue_text = "\n".join(f"- {i}" for i in issues) if issues else ""
    state[col] = {"check": check_name, "status": status, "issues": issue_text, "updated": now}
    _save_report(state, table, output_dir, list(df.columns))
    return status, issues


def _print_result(check, col, status, issues):
    print(f"[Valitine] {check}(`{col}`) → {status}")
    for issue in issues:
        print(f"           ↳ {issue}")


# ─────────────────────────────────────────────
# Public check functions
# ─────────────────────────────────────────────

def check_age(df: pd.DataFrame, col: str, table: str,
              min_age: int = 0, max_age: int = 120,
              output_dir: str = "reports") -> dict:
    """Check age column: valid numeric range, no non-numeric values."""
    series = df[col]
    issues = []

    non_numeric = pd.to_numeric(series, errors="coerce").isna() & series.notna()
    non_numeric_ids = df[non_numeric].index.tolist()
    if non_numeric_ids:
        issues.append(f"พบค่าที่ไม่ใช่ตัวเลข {len(non_numeric_ids)} rows — index: {non_numeric_ids[:10]}")

    numeric_series = pd.to_numeric(series, errors="coerce").dropna()
    out_of_range = numeric_series[(numeric_series < min_age) | (numeric_series > max_age)]
    if not out_of_range.empty:
        issues.append(f"ค่านอก range [{min_age}–{max_age}]: {len(out_of_range)} rows — index: {out_of_range.index.tolist()[:10]}")

    status, _ = _update_col(df, col, table, output_dir, "check_age", issues, passed=len(issues) == 0)
    _print_result("check_age", col, status, issues)
    return {"column": col, "status": status, "issues": issues}


def check_email(df: pd.DataFrame, col: str, table: str,
                output_dir: str = "reports") -> dict:
    """Check email format."""
    series = df[col].dropna()
    pattern = r"^[\w\.\+\-]+@[\w\-]+\.[a-zA-Z]{2,}$"
    invalid = series[~series.astype(str).str.match(pattern, na=False)]
    issues = []
    if not invalid.empty:
        issues.append(f"format ไม่ถูกต้อง {len(invalid)} rows — index: {invalid.index.tolist()[:10]}")
    status, _ = _update_col(df, col, table, output_dir, "check_email", issues, passed=len(issues) == 0)
    _print_result("check_email", col, status, issues)
    return {"column": col, "status": status, "issues": issues}


def check_phone(df: pd.DataFrame, col: str, table: str,
                output_dir: str = "reports") -> dict:
    """Check phone number format."""
    series = df[col].dropna().astype(str)
    pattern = r"^\+?[\d\s\-]{9,15}$"
    invalid = series[~series.str.match(pattern, na=False)]
    issues = []
    if not invalid.empty:
        issues.append(f"format ไม่ถูกต้อง {len(invalid)} rows — index: {invalid.index.tolist()[:10]}")
    status, _ = _update_col(df, col, table, output_dir, "check_phone", issues, passed=len(issues) == 0)
    _print_result("check_phone", col, status, issues)
    return {"column": col, "status": status, "issues": issues}


def check_date(df: pd.DataFrame, col: str, table: str,
               allow_future: bool = False,
               output_dir: str = "reports") -> dict:
    """Check date column: parseable and no unexpected future dates."""
    series = df[col]
    issues = []
    parsed = pd.to_datetime(series, errors="coerce")
    unparseable = series[parsed.isna() & series.notna()]
    if not unparseable.empty:
        issues.append(f"parse ไม่ได้ {len(unparseable)} rows — index: {unparseable.index.tolist()[:10]}")
    if not allow_future:
        future = parsed[parsed > pd.Timestamp.now()]
        if not future.empty:
            issues.append(f"พบวันที่อยู่ในอนาคต {len(future)} rows — index: {future.index.tolist()[:10]}")
    status, _ = _update_col(df, col, table, output_dir, "check_date", issues, passed=len(issues) == 0)
    _print_result("check_date", col, status, issues)
    return {"column": col, "status": status, "issues": issues}


def check_category(df: pd.DataFrame, col: str, table: str,
                   allowed: list,
                   output_dir: str = "reports") -> dict:
    """Check column values are within an allowed set."""
    series = df[col].dropna()
    invalid = series[~series.isin(allowed)]
    issues = []
    if not invalid.empty:
        unexpected = invalid.unique().tolist()[:10]
        issues.append(f"พบค่านอก allowed list {len(invalid)} rows — ค่าที่พบ: {unexpected}")
    status, _ = _update_col(df, col, table, output_dir, f"check_category", issues, passed=len(issues) == 0)
    _print_result("check_category", col, status, issues)
    return {"column": col, "status": status, "issues": issues}


def check_range(df: pd.DataFrame, col: str, table: str,
                min_val=None, max_val=None,
                output_dir: str = "reports") -> dict:
    """Check numeric column is within a custom range."""
    series = pd.to_numeric(df[col], errors="coerce")
    issues = []
    if min_val is not None:
        below = series[series < min_val]
        if not below.empty:
            issues.append(f"ต่ำกว่า min ({min_val}): {len(below)} rows — index: {below.index.tolist()[:10]}")
    if max_val is not None:
        above = series[series > max_val]
        if not above.empty:
            issues.append(f"สูงกว่า max ({max_val}): {len(above)} rows — index: {above.index.tolist()[:10]}")
    status, _ = _update_col(df, col, table, output_dir, f"check_range({min_val},{max_val})", issues, passed=len(issues) == 0)
    _print_result("check_range", col, status, issues)
    return {"column": col, "status": status, "issues": issues}


def skip(df: pd.DataFrame, col: str, table: str,
         reason: str = "", output_dir: str = "reports"):
    """Mark a column as intentionally skipped."""
    state = _load_or_init_report(df, table, output_dir)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    state[col] = {"check": "— skip", "status": "— skip", "issues": reason, "updated": now}
    _save_report(state, table, output_dir, list(df.columns))
    print(f"[Valitine] `{col}` marked as skip")
